# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: instalando pipenv
      run: |
        sudo apt update
        sudo apt upgrade
        pip install pipenv
    - name: instalando bibliotecas de desenvolvimento
      run: pipenv install -r requirements-dev.txt codecov
    - name: rodando flake8
      run: |
        pipenv run flake8
    - name: rodando pytest
      run:  pipenv run pytest libpytools --cov=libpytools
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1